### PR TITLE
ChatOps - Sort thread comments by date

### PR DESCRIPTION
**Pull request by DaveW-STFC**
Adjusted ChatOps to use the datetime module and then sort the collected PRs by date before posting to slack.
Tests have also been updated.

### CODE REVIEW

**Review by khalford — CHANGES_REQUESTED** [review]
Can you update the `version.txt` and `docker-compose.yaml`? I would sugest it's a major change. You can read about SemVer [here ](https://semver.org/) if you're not familiar.

**Comment by meoflynn** [comment]
Looks good to me so far. There seems to be one unit test that is failing currently, could you have a look at the unit test?

**Comment by khalford** [comment]
> Looks good to me so far. There seems to be one unit test that is failing currently, could you have a look at the unit test?

@DaveW-STFC This might be due to the 90 to 30 day change you rebased onto. Hence the mock data isn't old / new enough.
`created_at=datetime.datetime(2024, 8, 9, 21, 49, 43, 845718)`

**Comment by DaveW-STFC** [comment]
> > Looks good to me so far. There seems to be one unit test that is failing currently, could you have a look at the unit test?
> 
> @DaveW-STFC This might be due to the 90 to 30 day change you rebased onto. Hence the mock data isn't old / new enough. `created_at=datetime.datetime(2024, 8, 9, 21, 49, 43, 845718)`

Thanks both, i have got this changed locally but planned to check in with you this afternoon that it should now be 30 days.

**Review by khalford — APPROVED** [review]
Awesome stuff. Thanks for doing this.

**Review by meoflynn — APPROVED** [review]

**Pull request merged**
