### PR TITLE
mirror official CIL image

### PR DESCRIPTION
**Pull request by casperdcl**
Part of https://github.com/TomographicImaging/CIL/issues/1639

### CODE REVIEW

**Comment by DavidFair** [comment]
@casperdcl is this to replicate the image from `ghcr.io` without any additional changes, or do you plan on extending this here in the future?

If it's just for replication into Harbor, I'd propose we remove the docker file and use the built-in replication tools within the service. Alternatively, you can push directly to Harbor from that repo too, since you have a project owned by the group (or we can set one up too)

We're happy to do that, this repo is an option for people who don't want to manage their own images. If you're maintaining it and regularly building/patching elsewhere I'm happy to defer to that too

**Comment by casperdcl** [comment]
> replicate the image from `ghcr.io` without any additional changes

Exactly.

> built-in replication tools within the service.

Oh, do you have a link to docs/examples?

> Alternatively, you can push directly to Harbor from that repo too [...] this repo is an option for people who don't want to manage their own images.

Sure, though I though this repo might be a nice centralised place (registry) to manage all harbour sources?

lemme know what you prefer, I'm happy with any sane solution.

**Comment by DavidFair** [comment]
https://goharbor.io/docs/2.9.0/administration/configuring-replication/create-replication-rules/

I'd check with your team if you have a project on Harbor - if so the admin/maintainer can set this up (we let users administer their own projects on Harbor)
If you don't have a project feel free to [contact us](https://stfc.atlassian.net/wiki/spaces/CLOUDKB/pages/248807458/Contact+Us) about getting one setup for you to replicate into...etc.

**Comment by DavidFair** [comment]
Closing this, as we ended up going down the replication route

**Pull request closed without merging**
